- name: 'Configure Bitcoin'
  ansible.builtin.copy:
    src: '{{ bitcoin_conf_src }}'
    dest: '{{ bitcoin_datadir }}/bitcoin.conf'
    owner: '{{ bitcoin_user }}'
    group: '{{ bitcoin_group }}'
    remote_src: yes

- name: 'Create bitcoin conf dir'
  ansible.builtin.file:
    path: '{{ bitcoin_conf_link }}'
    state: directory
    recurse: yes
    owner: '{{ bitcoin_user }}'
    group: '{{ bitcoin_group }}'

- name: 'Create bitcoin.conf symlink'
  ansible.builtin.file:
    path: '{{ bitcoin_conf_link }}bitcoin.conf'
    src: '{{ bitcoin_datadir }}/bitcoin.conf'
    state: link
